version: '3.9'

services:
  portfolio:
    build: .
    image: jonhef-portfolio
    container_name: jonhef-portfolio
    ports:
      - "5173:5173"
    volumes:
      # Используем уже существующие сертификаты на сервере (пример для Let's Encrypt):
      - /etc/ssl/cloudflare/origin.pem;
      - /etc/ssl/cloudflare/origin.key;
    restart: unless-stopped
